# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: GithubRelease@1
  displayName: 'Publishing artifact'
  inputs:
    gitHubConnection: ucpdh23_repo
    repositoryName: ucpdh23/servant
    assets: $(Build.Repository.LocalPath)/target/servantV3-0.0.1-SNAPSHOT-fat.jar
    action: edit
    target: '$(Build.SourceVersion)'
    tag: $(Build.BuildNumber)
